package com.erumpay.payment.core.exception;

import org.springframework.http.HttpStatus;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {

        // CORE: 공통 요청 검증 오류.
        BAD_REQUEST(HttpStatus.BAD_REQUEST, "PAY-CORE-001", "CORE_INVALID_REQUEST", "결제 요청 값을 확인해 주세요."),

        // CORE: 결제 준비, 실행 요청 검증 오류.
        AMOUNT_MISMATCH(HttpStatus.BAD_REQUEST, "PAY-CORE-002", "PAYMENT_AMOUNT_MISMATCH", "결제 금액이 일치하지 않습니다."),
        INVALID_IDEMPOTENCY_KEY(HttpStatus.BAD_REQUEST, "PAY-CORE-003", "PAYMENT_IDEMPOTENCY_KEY_INVALID",
                        "멱등성 키 형식이 잘못되었습니다."),
        PAYMENT_TYPE_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-004", "PAYMENT_TYPE_INVALID",
                        "결제 타입은 SINGLE, DUTCH, REMOTE 중 하나여야 합니다."),
        PAYMENT_CARD_AMOUNT_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-009", "PAYMENT_CARD_AMOUNT_INVALID",
                        "카드별 결제 금액을 확인해 주세요."),
        PAYMENT_CARD_DUPLICATED(HttpStatus.BAD_REQUEST, "PAY-CORE-010", "PAYMENT_CARD_DUPLICATED",
                        "같은 카드가 중복 요청되었습니다."),
        PAYMENT_IDEMPOTENCY_KEY_MISMATCH(HttpStatus.BAD_REQUEST, "PAY-CORE-011", "PAYMENT_IDEMPOTENCY_KEY_MISMATCH",
                        "처음 요청한 멱등성 키와 다릅니다."),
        PAYMENT_REQUEST_BODY_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-013", "PAYMENT_REQUEST_BODY_INVALID",
                        "결제 요청 본문을 확인해 주세요."),
        PAYMENT_PIN_REQUIRED(HttpStatus.BAD_REQUEST, "PAY-CORE-014", "PAYMENT_PIN_REQUIRED", "결제 비밀번호를 입력해 주세요."),
        PAYMENT_CARD_LIST_REQUIRED(HttpStatus.BAD_REQUEST, "PAY-CORE-015", "PAYMENT_CARD_LIST_REQUIRED",
                        "결제할 카드를 1개 이상 선택해 주세요."),
        REQUEST_PARAMETER_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-017", "REQUEST_PARAMETER_INVALID", "요청 파라미터를 확인해 주세요."),
        REQUEST_HEADER_REQUIRED(HttpStatus.BAD_REQUEST, "PAY-CORE-018", "REQUEST_HEADER_REQUIRED", "필수 요청 헤더가 누락되었습니다."),
        REQUEST_METHOD_NOT_SUPPORTED(HttpStatus.METHOD_NOT_ALLOWED, "PAY-CORE-019", "REQUEST_METHOD_NOT_SUPPORTED", "지원하지 않는 요청 방식입니다."),

        // CORE: 결제 조회 조건 검증 오류.
        PAYMENT_STATUS_FILTER_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-005", "PAYMENT_STATUS_FILTER_INVALID",
                        "조회 상태는 ALL, PAID, CANCELED 중 하나여야 합니다."),
        PAYMENT_PERIOD_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-006", "PAYMENT_PERIOD_INVALID",
                        "조회 기간 조건을 확인해 주세요."),
        PAYMENT_DATE_RANGE_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-007", "PAYMENT_DATE_RANGE_INVALID",
                        "조회 시작일과 종료일을 확인해 주세요."),
        PAYMENT_STRATEGY_TYPE_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-008", "PAYMENT_STRATEGY_TYPE_INVALID",
                        "조회 적용유형 값을 확인해 주세요."),
        PAYMENT_PAGE_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-012", "PAYMENT_PAGE_INVALID", "페이지 번호는 0 이상이어야 합니다."),
        PAYMENT_TYPE_FILTER_INVALID(HttpStatus.BAD_REQUEST, "PAY-CORE-016", "PAYMENT_TYPE_FILTER_INVALID",
                        "조회 결제 타입은 ALL, SINGLE, DUTCH, REMOTE 중 하나여야 합니다."),

        // CORE: 인증, 인가, 소유권 오류.
        FORBIDDEN(HttpStatus.FORBIDDEN, "PAY-CORE-101", "PAYMENT_ACCESS_DENIED", "접근할 수 없는 결제입니다."),
        PAYMENT_OWNER_MISMATCH(HttpStatus.FORBIDDEN, "PAY-CORE-102", "PAYMENT_OWNER_MISMATCH", "본인 결제만 처리할 수 있습니다."),
        MERCHANT_API_KEY_MISSING(HttpStatus.UNAUTHORIZED, "PAY-CORE-103", "MERCHANT_API_KEY_MISSING",
                        "가맹점 API 키가 필요합니다."),
        MERCHANT_API_KEY_INVALID(HttpStatus.UNAUTHORIZED, "PAY-CORE-104", "MERCHANT_API_KEY_INVALID",
                        "가맹점 API 키를 확인해 주세요."),
        PAYMENT_USER_REQUIRED(HttpStatus.UNAUTHORIZED, "PAY-CORE-105", "PAYMENT_USER_REQUIRED", "사용자 정보가 필요합니다."),

        // CORE: 리소스 없음, 상태 전이 오류.
        PAY_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-CORE-201", "PAYMENT_NOT_FOUND", "결제 정보를 찾을 수 없습니다."),
        PAYMENT_STATUS_NOT_PREPARABLE(HttpStatus.CONFLICT, "PAY-CORE-202", "PAYMENT_STATUS_NOT_PREPARABLE",
                        "현재 상태에서는 결제 준비를 할 수 없습니다."),
        PAYMENT_STATUS_NOT_PAYABLE(HttpStatus.CONFLICT, "PAY-CORE-203", "PAYMENT_STATUS_NOT_PAYABLE",
                        "현재 상태에서는 결제를 할 수 없습니다."),
        CANCELED_INVALID(HttpStatus.CONFLICT, "PAY-CORE-204", "PAYMENT_CANCEL_NOT_ALLOWED", "취소할 수 없는 결제입니다."),
        CANCELED_CARD_INVALID(HttpStatus.NOT_FOUND, "PAY-CORE-205", "PAYMENT_CANCEL_CARD_NOT_FOUND",
                        "취소할 카드 결제를 찾을 수 없습니다."),
        PAYMENT_HISTORY_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-CORE-206", "PAYMENT_HISTORY_NOT_FOUND",
                        "결제 내역을 찾을 수 없습니다."),
        PAYMENT_DUTCH_LINK_INVALID(HttpStatus.CONFLICT, "PAY-CORE-207", "PAYMENT_DUTCH_LINK_INVALID",
                        "더치페이 연결 정보를 확인해 주세요."),
        PAYMENT_REMOTE_LINK_INVALID(HttpStatus.CONFLICT, "PAY-CORE-208", "PAYMENT_REMOTE_LINK_INVALID",
                        "원격결제 연결 정보를 확인해 주세요."),
        REQUEST_PATH_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-CORE-209", "REQUEST_PATH_NOT_FOUND", "요청 경로를 찾을 수 없습니다."),

        // CORE: 멱등성, 중복, 동시성 충돌 오류.
        DUPLICATED_REQUEST(HttpStatus.CONFLICT, "PAY-CORE-301", "PAYMENT_IDEMPOTENCY_CONFLICT", "중복된 결제 요청입니다."),
        REQUEST_IN_PROGRESS(HttpStatus.CONFLICT, "PAY-CORE-302", "PAYMENT_REQUEST_IN_PROGRESS", "결제 요청이 처리 중입니다."),
        PAYMENT_CONCURRENT_UPDATE_CONFLICT(HttpStatus.CONFLICT, "PAY-CORE-303", "PAYMENT_CONCURRENT_UPDATE_CONFLICT",
                        "결제가 다른 요청에서 먼저 변경되었습니다."),
        PAYMENT_ALREADY_PROCESSED(HttpStatus.CONFLICT, "PAY-CORE-304", "PAYMENT_ALREADY_PROCESSED", "이미 처리된 결제입니다."),

        // CORE: 외부 인증 연동 오류.
        MERCHANT_AUTH_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "PAY-CORE-401", "MERCHANT_AUTH_UNAVAILABLE",
                        "가맹점 인증 서비스 연결에 실패했습니다."),

        // CORE: SSE 전파 오류.
        CORE_SSE_PUBLISH_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-CORE-501", "CORE_SSE_PUBLISH_FAILED",
                        "결제 상태 발행에 실패했습니다."),
        CORE_SSE_SEND_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-CORE-502", "CORE_SSE_SEND_FAILED",
                        "결제 실시간 전송에 실패했습니다."),

        // CORE: 내부 처리, 저장 오류.
        INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-CORE-900", "CORE_INTERNAL_ERROR",
                        "결제 서버 내부 오류입니다."),
        PAYMENT_STATE_INVALID(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-CORE-901", "PAYMENT_STATE_INVALID",
                        "저장된 결제 상태를 처리할 수 없습니다."),
        PAYMENT_EVENT_SAVE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-CORE-902", "PAYMENT_EVENT_SAVE_FAILED",
                        "결제 이벤트 저장에 실패했습니다."),
        PAYMENT_CARD_DETAIL_SAVE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-CORE-903",
                        "PAYMENT_CARD_DETAIL_SAVE_FAILED", "결제 카드 내역 저장에 실패했습니다."),

        // QR: core에서 주문번호 생성과 QR 기반 결제 생성에 사용하는 QrService 의존성 오류.
        QR_INVALID(HttpStatus.BAD_REQUEST, "PAY-QR-001", "QR_INVALID_TOKEN", "QR 토큰을 확인해 주세요."),
        QR_TOKEN_REQUIRED(HttpStatus.BAD_REQUEST, "PAY-QR-002", "QR_TOKEN_REQUIRED", "QR 토큰을 입력해 주세요."),
        QR_REQUEST_INVALID(HttpStatus.BAD_REQUEST, "PAY-QR-003", "QR_REQUEST_INVALID", "QR 요청 값을 확인해 주세요."),
        QR_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-QR-201", "QR_NOT_FOUND", "QR 정보를 찾을 수 없습니다."),
        QR_EXPIRED(HttpStatus.GONE, "PAY-QR-202", "QR_EXPIRED", "QR 토큰이 만료되었습니다."),
        QR_USED(HttpStatus.GONE, "PAY-QR-203", "QR_USED", "이미 사용된 QR 토큰입니다."),
        QR_ORDER_NO_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-QR-900", "QR_ORDER_NO_GENERATION_FAILED",
                        "QR 주문번호 생성에 실패했습니다."),

        // DUT: core 결제 준비와 결제 결과 처리 흐름에서 사용하는 DutchPayService 의존성 오류.
        DUTCH_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "PAY-DUT-001", "DUTCH_INVALID_REQUEST", "더치페이 요청 값을 확인해 주세요."),
        DUTCH_INVALID_AMOUNT(HttpStatus.BAD_REQUEST, "PAY-DUT-002", "DUTCH_INVALID_AMOUNT", "더치페이 금액을 확인해 주세요."),
        DUTCH_SPLIT_METHOD_INVALID(HttpStatus.BAD_REQUEST, "PAY-DUT-003", "DUTCH_SPLIT_METHOD_INVALID",
                        "더치페이 분할 방식을 확인해 주세요."),
        DUTCH_PARTICIPANT_COUNT_INVALID(HttpStatus.BAD_REQUEST, "PAY-DUT-004", "DUTCH_PARTICIPANT_COUNT_INVALID",
                        "더치페이 참여자 수를 확인해 주세요."),
        DUTCH_INVITE_TOKEN_INVALID(HttpStatus.BAD_REQUEST, "PAY-DUT-005", "DUTCH_INVITE_TOKEN_INVALID",
                        "더치페이 초대 링크를 확인해 주세요."),
        DUTCH_PAYMENT_STATUS_INVALID(HttpStatus.BAD_REQUEST, "PAY-DUT-006", "DUTCH_PAYMENT_STATUS_INVALID",
                        "더치페이 결제 상태를 확인해 주세요."),
        DUTCH_ACCESS_DENIED(HttpStatus.FORBIDDEN, "PAY-DUT-101", "DUTCH_ACCESS_DENIED", "더치페이 접근 권한이 없습니다."),
        DUTCH_HOST_ONLY_ACTION(HttpStatus.FORBIDDEN, "PAY-DUT-102", "DUTCH_HOST_ONLY_ACTION", "더치페이 대표자만 가능합니다."),
        DUTCH_PARTICIPANT_ONLY_ACTION(HttpStatus.FORBIDDEN, "PAY-DUT-103", "DUTCH_PARTICIPANT_ONLY_ACTION",
                        "더치페이 참여자만 가능합니다."),
        DUTCH_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-DUT-201", "DUTCH_SESSION_NOT_FOUND", "더치페이 세션을 찾을 수 없습니다."),
        DUTCH_PARTICIPANT_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-DUT-202", "DUTCH_PARTICIPANT_NOT_FOUND",
                        "더치페이 참여자를 찾을 수 없습니다."),
        DUTCH_SESSION_NOT_IN_PROGRESS(HttpStatus.CONFLICT, "PAY-DUT-203", "DUTCH_SESSION_NOT_IN_PROGRESS",
                        "진행 중인 더치페이 세션이 아닙니다."),
        DUTCH_SESSION_ALREADY_COMPLETED(HttpStatus.CONFLICT, "PAY-DUT-204", "DUTCH_SESSION_ALREADY_COMPLETED",
                        "이미 완료된 더치페이 세션입니다."),
        DUTCH_SESSION_FAILED(HttpStatus.CONFLICT, "PAY-DUT-205", "DUTCH_SESSION_FAILED", "실패한 더치페이 세션입니다."),
        DUTCH_SESSION_TIMEOUT_HANDLED(HttpStatus.CONFLICT, "PAY-DUT-206", "DUTCH_SESSION_TIMEOUT_HANDLED",
                        "타임아웃 처리된 더치페이 세션입니다."),
        DUTCH_HOST_AUTH_NOT_CREATED(HttpStatus.CONFLICT, "PAY-DUT-207", "DUTCH_HOST_AUTH_NOT_CREATED",
                        "대표자 가승인 결제를 찾을 수 없습니다."),
        DUTCH_PARTICIPANT_NOT_PAYABLE(HttpStatus.CONFLICT, "PAY-DUT-208", "DUTCH_PARTICIPANT_NOT_PAYABLE",
                        "현재 참여자는 결제할 수 없습니다."),
        DUTCH_AMOUNT_MISMATCH(HttpStatus.CONFLICT, "PAY-DUT-209", "DUTCH_AMOUNT_MISMATCH", "더치페이 결제 금액이 일치하지 않습니다."),
        DUTCH_PAYMENT_ALREADY_LINKED(HttpStatus.CONFLICT, "PAY-DUT-210", "DUTCH_PAYMENT_ALREADY_LINKED",
                        "이미 연결된 더치페이 결제입니다."),
        DUTCH_INVITE_TOKEN_EXPIRED(HttpStatus.GONE, "PAY-DUT-211", "DUTCH_INVITE_TOKEN_EXPIRED",
                        "더치페이 초대 링크가 만료되었습니다."),
        DUTCH_FINAL_PAYMENT_NOT_READY(HttpStatus.CONFLICT, "PAY-DUT-212", "DUTCH_FINAL_PAYMENT_NOT_READY",
                        "대표자 최종 결제를 아직 진행할 수 없습니다."),
        DUTCH_DUPLICATED_PARTICIPANT(HttpStatus.CONFLICT, "PAY-DUT-301", "DUTCH_DUPLICATED_PARTICIPANT",
                        "이미 참여 중인 사용자입니다."),
        DUTCH_CONCURRENT_UPDATE_CONFLICT(HttpStatus.CONFLICT, "PAY-DUT-302", "DUTCH_CONCURRENT_UPDATE_CONFLICT",
                        "더치페이 정보가 동시에 변경되었습니다."),
        DUTCH_DUPLICATED_PAYMENT(HttpStatus.CONFLICT, "PAY-DUT-303", "DUTCH_DUPLICATED_PAYMENT", "중복된 더치페이 결제입니다."),
        DUTCH_HOST_AUTH_REJECTED(HttpStatus.PAYMENT_REQUIRED, "PAY-DUT-401", "DUTCH_HOST_AUTH_REJECTED",
                        "대표자 가승인이 거절되었습니다."),
        DUTCH_HOST_AUTH_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "PAY-DUT-402", "DUTCH_HOST_AUTH_UNAVAILABLE",
                        "대표자 가승인 처리에 실패했습니다."),
        DUTCH_PG_RESULT_SYNC_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-DUT-403", "DUTCH_PG_RESULT_SYNC_FAILED",
                        "더치페이 결제 결과 반영에 실패했습니다."),
        DUTCH_SSE_PUBLISH_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-DUT-501", "DUTCH_SSE_PUBLISH_FAILED",
                        "더치페이 상태 전파에 실패했습니다."),
        DUTCH_NOTIFICATION_PUBLISH_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-DUT-502",
                        "DUTCH_NOTIFICATION_PUBLISH_FAILED", "더치페이 알림 발행에 실패했습니다."),
        DUTCH_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-DUT-900", "DUTCH_INTERNAL_ERROR", "더치페이 내부 오류입니다."),

        // RMT: core 결제 준비와 결제 결과 처리 흐름에서 사용하는 RemotePayService 의존성 오류.
        RMT_INVALID_REQUEST(HttpStatus.BAD_REQUEST, "PAY-RMT-001", "RMT_INVALID_REQUEST", "원격결제 요청 값을 확인해 주세요."),
        RMT_INVALID_AMOUNT(HttpStatus.BAD_REQUEST, "PAY-RMT-002", "RMT_INVALID_AMOUNT", "원격결제 금액을 확인해 주세요."),
        RMT_REQUESTER_TARGET_SAME(HttpStatus.BAD_REQUEST, "PAY-RMT-003", "RMT_REQUESTER_TARGET_SAME",
                        "요청자와 대리결제자가 같습니다."),
        RMT_TARGET_REQUIRED(HttpStatus.BAD_REQUEST, "PAY-RMT-004", "RMT_TARGET_REQUIRED", "대리결제자가 필요합니다."),
        RMT_PAYMENT_INVALID(HttpStatus.BAD_REQUEST, "PAY-RMT-005", "RMT_PAYMENT_INVALID", "원격결제 결제건을 확인해 주세요."),
        RMT_DESCRIPTION_INVALID(HttpStatus.BAD_REQUEST, "PAY-RMT-006", "RMT_DESCRIPTION_INVALID",
                        "원격결제 설명을 확인해 주세요."),
        RMT_EXPIRES_AT_INVALID(HttpStatus.BAD_REQUEST, "PAY-RMT-007", "RMT_EXPIRES_AT_INVALID",
                        "원격결제 만료 시간을 확인해 주세요."),
        RMT_ACCESS_DENIED(HttpStatus.FORBIDDEN, "PAY-RMT-101", "RMT_ACCESS_DENIED", "원격결제 접근 권한이 없습니다."),
        RMT_REQUESTER_ONLY_ACTION(HttpStatus.FORBIDDEN, "PAY-RMT-102", "RMT_REQUESTER_ONLY_ACTION", "원격결제 요청자만 가능합니다."),
        RMT_TARGET_ONLY_ACTION(HttpStatus.FORBIDDEN, "PAY-RMT-103", "RMT_TARGET_ONLY_ACTION", "대리결제자만 가능합니다."),
        RMT_FRIEND_NOT_ALLOWED(HttpStatus.FORBIDDEN, "PAY-RMT-104", "RMT_FRIEND_NOT_ALLOWED", "친구 관계가 확인되지 않았습니다."),
        RMT_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-RMT-201", "RMT_REQUEST_NOT_FOUND", "원격결제 요청을 찾을 수 없습니다."),
        RMT_SOURCE_PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-RMT-202", "RMT_SOURCE_PAYMENT_NOT_FOUND",
                        "원격결제 원본 결제를 찾을 수 없습니다."),
        RMT_REQUEST_NOT_DRAFT(HttpStatus.CONFLICT, "PAY-RMT-203", "RMT_REQUEST_NOT_DRAFT",
                        "현재 상태에서는 대리결제자를 지정할 수 없습니다."),
        RMT_REQUEST_NOT_PENDING(HttpStatus.CONFLICT, "PAY-RMT-204", "RMT_REQUEST_NOT_PENDING", "대기 중인 원격결제 요청이 아닙니다."),
        RMT_REQUEST_EXPIRED(HttpStatus.GONE, "PAY-RMT-205", "RMT_REQUEST_EXPIRED", "원격결제 요청이 만료되었습니다."),
        RMT_PAYMENT_NOT_CONNECTED(HttpStatus.CONFLICT, "PAY-RMT-206", "RMT_PAYMENT_NOT_CONNECTED",
                        "원격결제에 결제건이 연결되지 않았습니다."),
        RMT_PAYMENT_ALREADY_CONNECTED(HttpStatus.CONFLICT, "PAY-RMT-207", "RMT_PAYMENT_ALREADY_CONNECTED",
                        "이미 결제건이 연결된 원격결제입니다."),
        RMT_REQUEST_ALREADY_COMPLETED(HttpStatus.CONFLICT, "PAY-RMT-208", "RMT_REQUEST_ALREADY_COMPLETED",
                        "이미 완료된 원격결제입니다."),
        RMT_REQUEST_ALREADY_CANCELLED(HttpStatus.CONFLICT, "PAY-RMT-209", "RMT_REQUEST_ALREADY_CANCELLED",
                        "이미 취소된 원격결제입니다."),
        RMT_REQUEST_ALREADY_REJECTED(HttpStatus.CONFLICT, "PAY-RMT-210", "RMT_REQUEST_ALREADY_REJECTED",
                        "이미 거절된 원격결제입니다."),
        RMT_PAYMENT_AMOUNT_MISMATCH(HttpStatus.CONFLICT, "PAY-RMT-211", "RMT_PAYMENT_AMOUNT_MISMATCH",
                        "원격결제 금액이 일치하지 않습니다."),
        RMT_PAYMENT_TARGET_MISMATCH(HttpStatus.CONFLICT, "PAY-RMT-212", "RMT_PAYMENT_TARGET_MISMATCH",
                        "원격결제 대상자가 일치하지 않습니다."),
        RMT_SOURCE_PAYMENT_NOT_PAYABLE(HttpStatus.CONFLICT, "PAY-RMT-213", "RMT_SOURCE_PAYMENT_NOT_PAYABLE",
                        "원본 결제를 현재 처리할 수 없습니다."),
        RMT_DUPLICATED_REQUEST(HttpStatus.CONFLICT, "PAY-RMT-301", "RMT_DUPLICATED_REQUEST", "중복된 원격결제 요청입니다."),
        RMT_DUPLICATED_PAYMENT_LINK(HttpStatus.CONFLICT, "PAY-RMT-302", "RMT_DUPLICATED_PAYMENT_LINK",
                        "중복된 원격결제 연결입니다."),
        RMT_CONCURRENT_UPDATE_CONFLICT(HttpStatus.CONFLICT, "PAY-RMT-303", "RMT_CONCURRENT_UPDATE_CONFLICT",
                        "원격결제 정보가 동시에 변경되었습니다."),
        RMT_SSE_PUBLISH_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-RMT-501", "RMT_SSE_PUBLISH_FAILED",
                        "원격결제 상태 알림 발행에 실패했습니다."),
        RMT_SSE_SEND_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-RMT-502", "RMT_SSE_SEND_FAILED",
                        "원격결제 실시간 알림 전송에 실패했습니다."),
        RMT_NOTIFICATION_PUBLISH_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-RMT-503",
                        "RMT_NOTIFICATION_PUBLISH_FAILED", "원격결제 알림 발행에 실패했습니다."),
        RMT_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-RMT-900", "RMT_INTERNAL_ERROR", "원격결제 내부 오류입니다."),

        // PG: core 결제, 취소, 가승인 취소 흐름에서 사용하는 PgClient 의존성 오류.
        PG_REQUEST_INVALID(HttpStatus.BAD_REQUEST, "PAY-PG-001", "PG_INVALID_REQUEST", "PG 요청 값을 확인해 주세요."),
        PG_AUTHORIZATION_REQUIRED(HttpStatus.UNAUTHORIZED, "PAY-PG-100", "PG_AUTHORIZATION_REQUIRED",
                        "PG 인증 정보가 필요합니다."),
        PG_PAYMENT_TRANSACTION_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-PG-201", "PG_PAYMENT_NOT_FOUND",
                        "PG 결제 거래를 찾을 수 없습니다."),
        PG_TRANSACTION_STATE_INVALID(HttpStatus.CONFLICT, "PAY-PG-203", "PG_TRANSACTION_STATE_INVALID",
                        "현재 PG 거래 상태에서는 처리할 수 없습니다."),
        PG_PAYMENT_ALREADY_CANCELLED(HttpStatus.CONFLICT, "PAY-PG-204", "PG_PAYMENT_ALREADY_CANCELLED",
                        "이미 취소된 PG 결제 거래입니다."),
        PG_AUTH_ONLY_ALREADY_VOIDED(HttpStatus.CONFLICT, "PAY-PG-205", "PG_AUTH_ONLY_ALREADY_VOIDED",
                        "이미 해제된 PG 가승인 거래입니다."),
        PG_ORIGINAL_TRANSACTION_MISMATCH(HttpStatus.CONFLICT, "PAY-PG-206", "PG_ORIGINAL_TRANSACTION_MISMATCH",
                        "원거래 정보와 요청 정보가 다릅니다."),
        PG_DUPLICATE_IDEMPOTENCY_KEY(HttpStatus.CONFLICT, "PAY-PG-301", "PG_DUPLICATE_IDEMPOTENCY_KEY",
                        "이미 사용된 PG 멱등성 키입니다."),
        INTERNAL_PG_SERVER_ERROR(HttpStatus.SERVICE_UNAVAILABLE, "PAY-PG-401", "PG_SERVICE_UNAVAILABLE",
                        "PG 서비스 연결에 실패했습니다."),
        CANCELED_PG_REJECTED(HttpStatus.CONFLICT, "PAY-PG-402", "PG_CANCEL_REJECTED", "PG에서 결제 취소를 거절했습니다."),
        PG_PAYMENT_REJECTED(HttpStatus.PAYMENT_REQUIRED, "PAY-PG-403", "PG_PAYMENT_REJECTED", "PG에서 결제를 거절했습니다."),
        PG_PAYMENT_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "PAY-PG-404", "PG_PAYMENT_FAILED", "PG 결제 처리에 실패했습니다."),
        PG_PAYMENT_STATUS_INVALID(HttpStatus.BAD_GATEWAY, "PAY-PG-405", "PG_PAYMENT_STATUS_INVALID",
                        "PG 응답 상태를 확인해 주세요."),
        PG_CANCEL_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "PAY-PG-406", "PG_CANCEL_FAILED", "PG 결제 취소에 실패했습니다."),
        PG_AUTH_CANCEL_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "PAY-PG-407", "PG_AUTH_CANCEL_FAILED",
                        "PG 가승인 취소에 실패했습니다."),
        PG_COMPENSATION_CANCEL_FAILED(HttpStatus.BAD_GATEWAY, "PAY-PG-408", "PG_COMPENSATION_FAILED",
                        "PG 보상 처리에 실패했습니다."),
        PG_RESPONSE_INVALID(HttpStatus.BAD_GATEWAY, "PAY-PG-409", "PG_RESPONSE_INVALID", "PG 응답 값을 확인해 주세요."),
        PG_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "PAY-PG-410", "PG_TIMEOUT", "PG 응답 시간이 초과되었습니다."),
        PG_BILLING_KEY_CIRCUIT_OPEN(HttpStatus.SERVICE_UNAVAILABLE, "PAY-PG-411", "PG_BILLING_KEY_CIRCUIT_OPEN",
                        "PG 빌링키 서비스가 일시적으로 차단되었습니다."),
        PG_BILLING_KEY_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "PAY-PG-412", "PG_BILLING_KEY_TIMEOUT",
                        "PG 빌링키 서비스 응답 시간이 초과되었습니다."),
        PG_CARD_CIRCUIT_OPEN(HttpStatus.SERVICE_UNAVAILABLE, "PAY-PG-413", "PG_CARD_CIRCUIT_OPEN",
                        "PG 카드 승인 서비스가 일시적으로 차단되었습니다."),
        PG_CARD_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, "PAY-PG-414", "PG_CARD_TIMEOUT", "PG 카드 승인 응답 시간이 초과되었습니다."),
        PG_INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-PG-900", "PG_INTERNAL_ERROR", "PG 내부 오류가 발생했습니다."),

        // AUTH: core 결제 비밀번호 검증에서 사용하는 AuthClient 의존성 오류.
        AUTH_REQUEST_INVALID(HttpStatus.BAD_REQUEST, "PAY-AUTH-001", "AUTH_REQUEST_INVALID", "인증 요청 값을 확인해 주세요."),
        AUTH_ACCESS_DENIED(HttpStatus.FORBIDDEN, "PAY-AUTH-101", "AUTH_ACCESS_DENIED", "인증 서비스 접근 권한이 없습니다."),
        PIN_VERIFY_FAILED(HttpStatus.UNAUTHORIZED, "PAY-AUTH-102", "PIN_VERIFY_FAILED", "PIN이 일치하지 않습니다."),
        PIN_NOT_SET(HttpStatus.NOT_FOUND, "PAY-AUTH-201", "PIN_NOT_SET", "결제 비밀번호가 설정되지 않았습니다."),
        AUTH_USER_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-AUTH-202", "AUTH_USER_NOT_FOUND", "사용자 인증 정보를 찾을 수 없습니다."),
        PIN_LOCKED(HttpStatus.LOCKED, "PAY-AUTH-203", "PIN_LOCKED", "PIN 잠금 상태입니다."),
        PIN_RESET_REQUIRED(HttpStatus.LOCKED, "PAY-AUTH-204", "PIN_RESET_REQUIRED", "PIN 재설정이 필요합니다."),
        INTERNAL_AUTH_SERVER_ERROR(HttpStatus.SERVICE_UNAVAILABLE, "PAY-AUTH-401", "AUTH_SERVICE_UNAVAILABLE",
                        "인증 서비스 연결에 실패했습니다."),
        AUTH_PIN_VERIFY_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "PAY-AUTH-402", "AUTH_PIN_VERIFY_FAILED",
                        "결제 비밀번호 검증에 실패했습니다."),
        AUTH_FRIEND_VALIDATE_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "PAY-AUTH-403", "AUTH_FRIEND_VALIDATE_FAILED",
                        "친구 관계 검증에 실패했습니다."),
        AUTH_RESPONSE_INVALID(HttpStatus.BAD_GATEWAY, "PAY-AUTH-404", "AUTH_RESPONSE_INVALID", "인증 서비스 응답 값을 확인해 주세요."),

        // CARD: 빌링키 조회와 결제 결과 전달에서 사용하는 CardClient 의존성 오류.
        CARD_REQUEST_INVALID(HttpStatus.BAD_REQUEST, "PAY-CARD-001", "CARD_INVALID_REQUEST", "카드 요청 값을 확인해 주세요."),
        CARD_BILLING_KEY_INVALID(HttpStatus.BAD_REQUEST, "PAY-CARD-002", "CARD_BILLING_KEY_INVALID", "카드 빌링키를 확인해 주세요."),
        CARD_PAYMENT_RESULT_INVALID(HttpStatus.BAD_REQUEST, "PAY-CARD-003", "CARD_PAYMENT_RESULT_INVALID", "카드 결제 결과 요청 값을 확인해 주세요."),
        CARD_AUTHORIZATION_REQUIRED(HttpStatus.UNAUTHORIZED, "PAY-CARD-100", "CARD_AUTHORIZATION_REQUIRED", "카드 서비스 인증 정보가 필요합니다."),
        CARD_BILLING_KEY_NOT_FOUND(HttpStatus.CONFLICT, "PAY-CARD-201", "CARD_BILLING_KEY_NOT_FOUND", "카드 빌링키를 찾을 수 없습니다."),
        CARD_PAYMENT_CARD_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-CARD-202", "CARD_NOT_FOUND", "결제 카드를 찾을 수 없습니다."),
        CARD_USER_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-CARD-203", "CARD_USER_NOT_FOUND", "카드 서비스에서 사용자를 찾을 수 없습니다."),
        CARD_USER_NOT_ACTIVE(HttpStatus.CONFLICT, "PAY-CARD-204", "CARD_USER_NOT_ACTIVE", "카드 서비스 사용자가 활성 상태가 아닙니다."),
        CARD_NOT_ACTIVE(HttpStatus.CONFLICT, "PAY-CARD-205", "CARD_NOT_ACTIVE", "활성 상태의 카드만 결제할 수 있습니다."),
        CARD_BILLING_KEY_ISSUE_PENDING(HttpStatus.CONFLICT, "PAY-CARD-207", "CARD_BILLING_KEY_ISSUE_PENDING", "카드 빌링키 발급이 완료되지 않았습니다."),
        INTERNAL_CARD_SERVER_ERROR(HttpStatus.SERVICE_UNAVAILABLE, "PAY-CARD-400", "CARD_SERVICE_UNAVAILABLE", "카드 서비스 연결에 실패했습니다."),
        CARD_AUTH_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "PAY-CARD-401", "CARD_AUTH_SERVICE_UNAVAILABLE", "카드 서비스의 회원 정보 조회에 실패했습니다."),
        CARD_BILLING_KEY_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "PAY-CARD-404", "CARD_BILLING_KEY_SERVICE_UNAVAILABLE", "카드 빌링키 서비스를 사용할 수 없습니다."),
        CARD_BILLING_KEY_LOOKUP_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "PAY-CARD-406", "CARD_BILLING_KEY_LOOKUP_FAILED", "카드 빌링키 조회에 실패했습니다."),
        CARD_PAYMENT_RESULT_SEND_FAILED(HttpStatus.SERVICE_UNAVAILABLE, "PAY-CARD-407", "CARD_PAYMENT_RESULT_SEND_FAILED", "카드 결제 결과 전송에 실패했습니다."),
        CARD_INTERNAL_SERVER_ERROR(HttpStatus.BAD_GATEWAY, "PAY-CARD-409", "CARD_INTERNAL_SERVER_ERROR", "카드 서비스 내부 오류가 발생했습니다."),

        // REC: core 추천 흐름에서 사용하는 RecommendClient와 추천 캐시 오류.
        REC_REQUEST_INVALID(HttpStatus.BAD_REQUEST, "PAY-REC-001", "REC_INVALID_REQUEST", "추천 요청 값을 확인해 주세요."),
        RECOMMENDATION_SELECTION_INVALID(HttpStatus.BAD_REQUEST, "PAY-REC-002", "REC_SELECTION_INVALID",
                        "선택한 추천 결제 조합을 확인해 주세요."),
        REC_STRATEGY_INVALID(HttpStatus.BAD_REQUEST, "PAY-REC-003", "REC_STRATEGY_INVALID", "추천 전략 값을 확인해 주세요."),
        REC_CACHE_NOT_FOUND(HttpStatus.NOT_FOUND, "PAY-REC-201", "REC_CACHE_NOT_FOUND", "추천 결과를 찾을 수 없습니다."),
        REC_CARD_SERVICE_CLIENT_ERROR(HttpStatus.BAD_GATEWAY, "PAY-REC-400", "REC_CARD_SERVICE_CLIENT_ERROR",
                        "추천 서비스가 카드 서비스 응답을 처리하지 못했습니다."),
        REC_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "PAY-REC-401", "REC_SERVICE_UNAVAILABLE",
                        "추천 서비스를 일시적으로 사용할 수 없습니다."),
        REC_INTERNAL_SERVER_ERROR(HttpStatus.BAD_GATEWAY, "PAY-REC-402", "REC_INTERNAL_SERVER_ERROR",
                        "추천 서비스 내부 오류가 발생했습니다."),
        REC_RESPONSE_INVALID(HttpStatus.BAD_GATEWAY, "PAY-REC-403", "REC_RESPONSE_INVALID", "추천 서비스 응답 값을 확인해 주세요."),
        REC_CACHE_READ_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-REC-900", "REC_CACHE_READ_FAILED",
                        "추천 결과 조회에 실패했습니다."),
        REC_CACHE_WRITE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "PAY-REC-901", "REC_CACHE_WRITE_FAILED",
                        "추천 결과 저장에 실패했습니다.");

        private final HttpStatus status;
        private final String code;
        private final String reason;
        private final String message;
}
